package edu.wpi.first.wpilibj.util;

/**
 * Autogenerated file! Do not manually edit this file. This version is regenerated
 * any time the publish task is run, or when this file is deleted.
 */
public final class WPILibVersion {
  /** The version number. */
  public static final String Version = "2025.3.1";

  /** Utility class. */
  private WPILibVersion() {}
}
